"use client";
import AssetManagement from "./_components/AssetManagement";

const mockAssets = [
  {
    id: "MAC-2026-001",
    name: 'MacBook Pro 16"',
    sn: "C02ZX1ABCD",
    category: "MacBook",
    status: "Хуваарилсан",
    user: "T. Enkhjargal",
    dept: "Engineering",
    location: "HQ - Floor 3",
    price: "₮ 4,125,000",
    initial: "TE",
  },
  {
    id: "MAC-2026-002",
    name: 'MacBook Pro 14"',
    sn: "C02ZX1ABCE",
    category: "MacBook",
    status: "Сул",
    user: "-",
    dept: "",
    location: "Storage Room A",
    price: "₮ 3,515,000",
    initial: "",
  },
  {
    id: "LPT-2025-042",
    name: "Dell XPS 15",
    sn: "DELLXPS42ABC",
    category: "Laptop",
    status: "Засварт",
    user: "B. Ganzorig",
    dept: "Design",
    location: "Repair Center",
    price: "₮ 2,400,000",
    initial: "BG",
  },
  {
    id: "LPT-2025-04",
    name: "Dell XPS 15",
    sn: "DELLXPS42ABC",
    category: "Laptop",
    status: "Засварт",
    user: "B. Ganzorig",
    dept: "Design",
    location: "Repair Center",
    price: "₮ 2,400,000",
    initial: "BG",
  },
  {
    id: "LPT-2025-04w",
    name: "Dell XPS 15",
    sn: "DELLXPS42ABC",
    category: "Laptop",
    status: "Засварт",
    user: "B. Ganzorig",
    dept: "Design",
    location: "Repair Center",
    price: "₮ 2,400,000",
    initial: "BG",
  },
  {
    id: "LPT-2023-04",
    name: "Dell XPS 15",
    sn: "DELLXPS42ABC",
    category: "Laptop",
    status: "Засварт",
    user: "B. Ganzorig",
    dept: "Design",
    location: "Repair Center",
    price: "₮ 2,400,000",
    initial: "BG",
  },
  {
    id: "LPT-2024-04w",
    name: "Dell XPS 15",
    sn: "DELLXPS42ABC",
    category: "Laptop",
    status: "Засварт",
    user: "B. Ganzorig",
    dept: "Design",
    location: "Repair Center",
    price: "₮ 2,400,000",
    initial: "BG",
  },
];

export default function AdminAssetPage() {
  return <AssetManagement assets={mockAssets} />;
}
